export const theme = {
  colors: {
    primary: '#FFB800',
    primaryDark: '#E6A500',
    primaryLight: '#FFC933',
    dark: '#1A1A2E',
    darkCard: '#16213E',
    darkDeep: '#0F3460',
    surface: '#FFFFFF',
    surfaceAlt: '#F8F9FA',
    success: '#00C851',
    successLight: '#E8F9EE',
    danger: '#FF4444',
    dangerLight: '#FFECEC',
    warning: '#FF8800',
    text: '#1A1A2E',
    textLight: '#6B7280',
    textMuted: '#9CA3AF',
    border: '#E5E7EB',
    purple: '#6C3CE1',
    purpleLight: '#EDE9FB',
    teal: '#00BFA5',
    tealLight: '#E0F5F3',
    overlay: 'rgba(26, 26, 46, 0.85)',
    // New colors for home screen redesign
    lavender: '#E8EAF6',
    nightFareBg: '#F5F5F5',
    planCardBg: '#1A1A2E',
    planYellow: '#F5C518',
    pink: '#E91E63',
    pinkLight: '#FCE4EC',
  },
  spacing: { xs: 4, sm: 8, md: 16, lg: 24, xl: 32, xxl: 48 },
  radius: { sm: 8, md: 12, lg: 20, xl: 28, full: 9999 },
  shadows: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.06,
      shadowRadius: 4,
      elevation: 2,
    },
    card: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.10,
      shadowRadius: 8,
      elevation: 4,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 20,
      elevation: 10,
    },
  },
};

export default theme;
